#
# Module manifest for module 'PSGet_Observations'
#
# Generated by: Kevin LaRoche
#
# Generated on: 2019-11-26
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Observations.psm1'

# Version number of this module.
ModuleVersion = '1.8'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '69d23a79-42fb-4a40-b439-735477948d9d'

# Author of this module
Author = 'Kevin LaRoche'

# Company or vendor of this module
CompanyName = 'Department of National Defence'

# Copyright statement for this module
Copyright = '(c) 2019 Kevin LaRoche. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Functions to get and convert data from Sharepoint, csv and json. Templates folder allows the mass export of all SPLLCCT list data.
The json templates has a short form name for each SPLLCT. This is used to get the site path, List Name and column mapping.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'CredentialsManager'; GUID = '01c9c681-1bc7-49a5-afd7-38ea82d20870'; ModuleVersion = '1.1'; }, 
               @{ModuleName = 'SharePointSDK'; GUID = 'bd4390dc-a8ad-4bce-8d69-f53ccf8e4163'; ModuleVersion = '2.1.6'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'htmlagilitypack\lib\Net40-client\HtmlAgilityPack.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Set-Credential', 'Export-JsonToCsv', 'Export-CsvToJson', 
               'Export-SPListFieldNamesToCsv', 'Export-AllSPListFieldsToCsv', 
               'Export-SpListByShortName', 'Export-SPListToCsv'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'obs'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'SPLLCTList.json', 'Templates\SPLLCTList.json'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'SharePoint','Conversion','SharePoint Lists'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'file://dcs-prk-pv02890/imgdiv$/0_DGIMPD_DGRPGI/0_DPDCC/C2MP/DLLS/ConversionHelp/Index.html'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

